spring:
  application:
    name: Api-Gateway
  cloud:
    gateway:
      routes:
      - id:  login
        uri: http://localhost:8001/**
        predicates:
        - Path=/login/**

      - id: admin
        uri: http://localhost:8002/**
        predicates:
        - Path=/admin/**

      - id: hotel-Service
        uri: http://localhost:8003/**
        predicates:
        - Path=/hotel-service/**

      - id: booking-Service
        uri: http://localhost:8004/**
        predicates:
        - Path=/booking-service/**

      - id: room-Service
        uri: http://localhost:8006/**
        predicates:
        - Path=/room-service/**
     
        
   
    